apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: icmrabbitmq-app
spec:
  replicas: 3
  template:
    metadata:
      name: icmrabbitmq-app
      labels:
        run: clouddb-demo
    spec:
      containers:
      - name: cloudrabbitmq-nodejs-app
        image: "registry.ng.bluemix.net/algerlabs/icmrabbitmq" # Edit me
        imagePullPolicy: Always
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: binding-icm-rabbitmq # Edit me
              key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: cloudetcd-service
  labels:
    run: clouddb-demo
spec:
  type: NodePort
  selector:
    run: clouddb-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081