apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: icdmongodb-app
spec:
  replicas: 3
  template:
    metadata:
      name: icdmongodb-app
      labels:
        run: clouddb-demo
    spec:
      containers:
      - name: cloudmongodb-nodejs-app
        image: "<region>.icr.io/<namespace>/icdmongodb" # Edit me
        imagePullPolicy: Always
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: <mongodb-secret-name> # Edit me
              key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: cloudmongodb-service
  labels:
    run: clouddb-demo
spec:
  type: NodePort
  selector:
    run: clouddb-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081