apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: icdelasticsearch-app
spec:
  replicas: 3
  template:
    metadata:
      name: icdelasticsearch-app
      labels:
        run: clouddb-demo
    spec:
      containers:
      - name: cloudelasticsearch-nodejs-app
        image: "registry.ng.bluemix.net/<namespace>/icdes" # Edit me
        imagePullPolicy: Always
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: <elasticsearch-secret-name> # Edit me
              key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: cloudelasticsearch-service
  labels:
    run: clouddb-demo
spec:
  type: NodePort
  selector:
    run: clouddb-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081